name: MyPy

on:
  push:
  pull_request:
    branches: [ main ]

env:
  WORKING_DIRECTORY: "."
  MYPY_OUTPUT_FILENAME: "mypy.log"
  CUSTOM_FLAGS: "--python-version=3.9 --color-output --no-pretty --follow-imports=skip"
  CUSTOM_PACKAGES: |
    instructor/_types/_alias.py
    instructor/cli/cli.py
    instructor/cli/files.py
    instructor/cli/jobs.py
    instructor/cli/usage.py
    instructor/exceptions.py
    instructor/function_calls.py
    tests/test_function_calls.py

jobs:
  MyPy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Environment setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
      - name: Install dev dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt
      - name: Run Continuous Integration Action
        run: |
          export CUSTOM_PACKAGES="${{ env.CUSTOM_PACKAGES }}" &&
          export CUSTOM_FLAGS="${{ env.CUSTOM_FLAGS }}" &&
          curl -sSL https://raw.githubusercontent.com/gao-hongnan/omniverse/continuous-integration/scripts/devops/continuous-integration/type_mypy.sh |
          bash | tee ${{ env.WORKING_DIRECTORY }}/${{ env.MYPY_OUTPUT_FILENAME }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mypy-log
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.MYPY_OUTPUT_FILENAME }}