name: Ruff

on:
  push:
  pull_request:
    branches: [main]

env:
  WORKING_DIRECTORY: "."
  RUFF_OUTPUT_FILENAME: "ruff.log"
  CUSTOM_FLAGS: ""
  CUSTOM_PACKAGES: "instructor examples tests"

jobs:
  Ruff:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Environment setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Install the project
        run: uv sync --all-extras
      - name: Run Continuous Integration Action
        uses: astral-sh/ruff-action@v1
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ruff-log
          path: ${{ env.WORKING_DIRECTORY }}/${{ env.RUFF_OUTPUT_FILENAME }}
